### ISSUE TITLE
error_log reads: PHP Notice:  Trying to get property of non-object in /home/public_html/tumblrdl.php on line 545

### ISSUE THREAD

**Issue by viksra** [saeros/tumblrdl#1]
error_log reads:
**PHP Notice:  Trying to get property of non-object in /home/public_html/tumblrdl.php on line 545**

Line 545 of tumblrdl.php:
`        return $json_output->response->posts;`

Error/notice seems to occur on tumblr accounts that have text posts mixed in with image posts.

**Comment by yonicsurny** [comment]
Thank you for reporting this issue @viksra 

Do you have by any chance an example account on which the script produces this error?
It would be easier for me in order to be able to reproduce the issue and fix it.

Regards
